# |------------------------------------------------------------------------
# |                       CommandPanels Config File
# |                           By RockyHawk v6.0
# |               https://www.spigotmc.org/resources/67788/
# |
# |------------------------------------------------------------------------

# When disabled, custom commands to open panels will not be registered
custom-commands: true

# Will make console logs when panels are opened and closed
panel-snooper: false