# |------------------------------------------------------------------------
# |                       CommandPanels Config File
# |                           By RockyHawk v4.4
# | https://www.spigotmc.org/resources/command-panels-custom-guis.67788/
# |
# |        auto-update and minor-updates-only is HEAVILY RECOMMENDED
# |------------------------------------------------------------------------
config:
  refresh-panels: true
  panel-blocks: true
  ingame-editor: true
  hotbar-items: true
  custom-commands: true
  auto-register-commands: true
  refresh-delay: 4
  server-ping-timeout: 10
  stop-sound: true
  disabled-world-message: true
  update-notifications: true
  panel-snooper: false
  input-cancel: cancel
  input-cancelled: '&cCancelled!'
  input-message:
  - '%cp-tag%&aEnter Input for Command'
  - '&cType &4%cp-args% &cto Cancel the command'
  updater:
    auto-update: true
    minor-updates-only: true
  format:
    tag: '&6[&bCommandPanels&6]'
    perms: '&cNo permission.'
    reload: '&aReloaded.'
    nopanel: '&cPanel not found.'
    noitem: '&cPanel doesn''t have clickable item.'
    notitem: '&cPlayer not found.'
    error: '&cError found in config at'
    needmoney: '&cInsufficient Funds!'
    needmoney-token: '&cInsufficient Funds!'
    needitems: '&cInsufficient Items!'
    bought: '&aSuccessfully Bought For $%cp-args%'
    bought-token: '&aSuccessfully Bought For %cp-args% Token/s'
    sold: '&aSuccessfully Sold Item!'
    sold-token: '&aSuccessfully Sold Item!'
    offline: 'Offline'
    offlineHeadValue: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmU1Mjg2YzQ3MGY2NmZmYTFhMTgzMzFjYmZmYjlhM2MyYTQ0MjRhOGM3MjU5YzQ0MzZmZDJlMzU1ODJhNTIyIn19fQ=='
